### PR TITLE
Fixed proposing TLD

### PR DESCRIPTION
**Pull request by mchf**
bnc#923990

### CODE REVIEW

**Comment by kobliha** [comment]
LGTM - code-wise, but I'm afraid that logically: using empty domain in this case just will not work and maybe deserves error message instead of setting wrong option.

**Comment by mchf** [comment]
in my POV. Using empty domain is valid setup and should be handled in the module. Domain is not mandatory and even user can set hostname without domain part in /etc/hostname

**Comment by kobliha** [comment]
@mchf OK, then PLS merge. But I can't tell if that will actually work :)

**Comment by mvidner** [comment]
Travis does pass, but that is because the `testsuite` directory only has one manual test which is not run there.

It seems we should add this to all repos using Perl:
```bash
find -name \*pm | xargs -n1 perl -I src/modules/ -I /usr/share/YaST2/modules -c
```

> Bareword "Hostname::DefaultDomain" not allowed while "strict subs" in use at ./src/modules/AuthServer.pm line 2671.

The correct syntax is `Hostname->DefaultDomain()`.

**Comment by mvidner** [comment]
LGTM.

**Comment by mchf** [comment]
Thanks for reviews, I'm going to merge once travis is done.

**Pull request merged**
