### PR TITLE
bnc#905622 - Fix yast2-auth-server CA file location

### PR DESCRIPTION
**Pull request by rhabacker**
see https://bugzilla.novell.com/show_bug.cgi?id=905622

### CODE REVIEW

**Comment by teclator** [comment]
Just changelog and bump version is missed

**Comment by rhabacker** [comment]
Updated .changes and .spec

**Comment by jreidinger** [comment]
@HouzuoGuo please check

**Comment by HouzuoGuo** [comment]
works very well, thank you very much.

**Pull request merged**
