### PR TITLE
bnc#991677 - Fix broken detection of common server certificate CA file

### PR DESCRIPTION
**Pull request by rhabacker**
see https://bugzilla.suse.com/show_bug.cgi?id=991677

### CODE REVIEW

**Comment by imobachgs** [comment]
@rhabacker Do you plan to release a new version? In that case, please update .changes and .spec files.

**Comment by imobachgs** [comment]
On the other hand, the change looks good. Thanks!

**Comment by rhabacker** [comment]
Updated .changes and .spec

**Comment by jreidinger** [comment]
@HouzuoGuo please check it, thanks

**Comment by HouzuoGuo** [comment]
works very well, thank you very much.

**Pull request merged**
