### PR TITLE
Remove default values from typedef

### PR DESCRIPTION
**Pull request by HouzuoGuo**
Patch content was originally written by Richard Biener.

### CODE REVIEW

**Comment by jreidinger** [comment]
looks good, please add chagnes and increase version so it is send to factory.

**Comment by kobliha** [comment]
See for instance http://yastgithubio.readthedocs.org/en/latest/development/#automatic-submission
to get more info abut this auto-submission thing

**Comment by jreidinger** [comment]
LGTM

**Comment by HouzuoGuo** [comment]
My bad - forgot to increase version number. Please review.

**Comment by jreidinger** [comment]
looks good, feel free to merge ;)

**Pull request merged**
