### PR TITLE
Drop ca mgm

### PR DESCRIPTION
**Pull request by mcalmer**
yast2 ca-mangement module is broken and will not be fixed. It should get dropped.
This commit removes it from yast2-auth-server

### CODE REVIEW

**Comment by kobliha** [comment]
Where is a FATE Nr for this request?

**Comment by mcalmer** [comment]
It's not a feature, it is a fact.

**Comment by jsrain** [comment]
What is the fact?
Every functionality removal needs a Fate entry in order to be covered by release notes and for support to be aware.

**Comment by mcalmer** [comment]
Fate#319119: drop not functional yast2-ca-management

**Comment by jsrain** [comment]
Master is for both next openSUSE and SLE12-SP1 - in this case, I suggest you should branch the repository first. This feature is not filed or evaluated against SP1.

**Comment by mcalmer** [comment]
I will leave the git handing for the maintainer of yast2-auth-server. I created only a branch with the start of the work.

**Comment by mvidner** [comment]
SLE-12-SP1 does contain yast2-ca-management, so we must not merge this until the `SLE-12-SP1` branch is created.
Anyway, if that module should be dropped, there should be a corresponding PR in that module, and I see none: https://github.com/yast/yast-ca-management/pulls

**Comment by mvidner** [comment]
Ah, `master` will become SLE-12-SP2 anyway. So the relevant question is: will CA management be in SLE 13? That needs to be agreed on with its product management.

**Comment by mcalmer** [comment]
If they want, they need to find a new maintainer.

**Comment by mcalmer** [comment]
And what you mean with a pull request to drop a module.
A pull request with removing all files?

**Comment by lslezak** [comment]
What's the status here? The SP1 is already out...

@mcalmer: The dropped modules have just a short README in the `master` branch (like in https://github.com/yast/yast-bluetooth) so it's obvious that they are not maintained anymore.

**Comment by kobliha** [comment]
@lslezak Dropping CA Mgmt has to go through FATE, I'm afraid.

**Comment by mcalmer** [comment]
The fate exists as Fate#319119. But I think it should nobody hold back from removing the usage of it in the auth module :-)

**Comment by lslezak** [comment]
I'm not familiar with ca-mgmt nor auth-server modules, @HouzuoGuo or @varkoly, could you check this and merge it if possible? This PR is open for more than 1 year...

**Comment by HouzuoGuo** [comment]
CA management is no longer integrated with setting up ID management servers since SLES 15.

**Pull request closed without merging**
